kind: pipeline
name: default
 
steps: 
  - name: install
    image: node:latest
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn install --pure-lockfile

  - name: build
    image: node:latest
    group: testing
    commands:
      - yarn build
      
trigger:
  branch:
  - master
  event:
  - push
     
